platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0.3'
pod 'MSDynamicsDrawerViewController', '~> 1.3.0'
pod 'SpinKit', '~> 1.0.0'
pod 'TDImageColors', '~> 0.2'
pod 'UISS', :git => 'https://github.com/yeahdongcn/UISS.git'