platform :ios, '7.0'

pod 'AFNetworking'
pod 'Baidu-Maps-iOS-SDK', '~> 2.1.1'
pod 'ColorUtils'
pod 'MSDynamicsDrawerViewController', '~> 1.3.4'
pod 'SpinKit'
pod 'TDImageColors'
pod 'TestFlightSDK', '~> 2.2.1'
pod 'UISS', :git => 'https://github.com/yeahdongcn/UISS.git'

#end