platform :ios, '7.0'

pod 'AFNetworking'
pod 'Baidu-Maps-iOS-SDK'
pod 'ColorUtils'
pod 'CRToast', :git => 'https://github.com/yeahdongcn/CRToast.git'
pod 'JBChartView'
pod 'KNSemiModalViewController', :git => 'https://bitbucket.org/yeahdongcn/knsemimodalviewcontroller.git'
pod 'MSDynamicsDrawerViewController', '~> 1.3.4'
pod 'SpinKit'
pod 'TDImageColors'
pod 'TestFlightSDK'
pod 'UISS', :git => 'https://github.com/yeahdongcn/UISS.git'

#end